fix UnicodeEncodeError caused by non-ascii field name
File "Qgis2threejs\stylewidget.py", line 232, in setup
  comboBox.addItem(u'+"{0}"'.format(fieldName), HeightWidgetFunc.FIRST_ATTR_REL + index)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

- update warning message