check if attribute value for file path is NULL
Python error:
  File "Qgis2threejs\propertyreader.py", line 190, in values
    vals.append(os.path.join(widgetValues["editText"], f.attribute(fieldName).strip('"')))
  AttributeError: 'QPyNullVariant' object has no attribute 'strip'