update rubber bands when sampling mode has been changed
and fix the following error:
  File Qgis2threejs\qgis2threejsdialog.py, line 456, in clearRubberBands
    if self.rb_quads:
AttributeError: 'Qgis2threejsDialog' object has no attribute 'rb_quads'